[package]
name = "rusty_tools"
version = "0.2.0"
edition = "2021"
description = "A crate with simple yet useful tools for rust"
license = "Apache-2.0"
repository = "https://github.com/ambareeshravi/rusty_tools.git"

[dependencies]
